/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TwoPartnerSupplyChain } from './TwoPartnerSupplyChain.js';
export * as factories from './factories/index.js';
export { TwoPartnerSupplyChain__factory } from './factories/TwoPartnerSupplyChain__factory.js';