/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace TwoPartnerSupplyChain {
      
    export type ProductStruct = {id: BigNumberish, name: string, description: string, origin: string, createdBy: AddressLike, status: BigNumberish, createdAt: BigNumberish, exists: boolean}

    export type ProductStructOutput = [id: bigint, name: string, description: string, origin: string, createdBy: string, status: bigint, createdAt: bigint, exists: boolean] & {id: bigint, name: string, description: string, origin: string, createdBy: string, status: bigint, createdAt: bigint, exists: boolean }
  

    export type HistoryEntryStruct = {status: BigNumberish, actor: AddressLike, location: string, note: string, timestamp: BigNumberish}

    export type HistoryEntryStructOutput = [status: bigint, actor: string, location: string, note: string, timestamp: bigint] & {status: bigint, actor: string, location: string, note: string, timestamp: bigint }
  
    }

  export interface TwoPartnerSupplyChainInterface extends Interface {
    getFunction(nameOrSignature: "MAX_DESCRIPTION_LENGTH" | "MAX_LOCATION_LENGTH" | "MAX_NAME_LENGTH" | "MAX_NOTE_LENGTH" | "MAX_ORIGIN_LENGTH" | "MAX_PAGE_SIZE" | "completeProduct" | "createProduct" | "getPartnerRole" | "getProduct" | "getProductHistory" | "getProductHistoryEntry" | "getProductHistoryLength" | "getProducts" | "markAsReceived" | "markAsShipped" | "productCount" | "receiver" | "supplier"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ProductCreated" | "ProductStatusUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'MAX_DESCRIPTION_LENGTH', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_LOCATION_LENGTH', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_NAME_LENGTH', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_NOTE_LENGTH', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_ORIGIN_LENGTH', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_PAGE_SIZE', values?: undefined): string;
encodeFunctionData(functionFragment: 'completeProduct', values: [BigNumberish, string, string]): string;
encodeFunctionData(functionFragment: 'createProduct', values: [string, string, string, string, string]): string;
encodeFunctionData(functionFragment: 'getPartnerRole', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getProduct', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getProductHistory', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getProductHistoryEntry', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getProductHistoryLength', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getProducts', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'markAsReceived', values: [BigNumberish, string, string]): string;
encodeFunctionData(functionFragment: 'markAsShipped', values: [BigNumberish, string, string]): string;
encodeFunctionData(functionFragment: 'productCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'receiver', values?: undefined): string;
encodeFunctionData(functionFragment: 'supplier', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'MAX_DESCRIPTION_LENGTH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_LOCATION_LENGTH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_NAME_LENGTH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_NOTE_LENGTH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_ORIGIN_LENGTH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_PAGE_SIZE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'completeProduct', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createProduct', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPartnerRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProduct', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProductHistory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProductHistoryEntry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProductHistoryLength', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProducts', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'markAsReceived', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'markAsShipped', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'productCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'receiver', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supplier', data: BytesLike): Result;
  }

  
    export namespace ProductCreatedEvent {
      export type InputTuple = [productId: BigNumberish, name: string, supplier: AddressLike, origin: string, location: string, note: string, timestamp: BigNumberish];
      export type OutputTuple = [productId: bigint, name: string, supplier: string, origin: string, location: string, note: string, timestamp: bigint];
      export interface OutputObject {productId: bigint, name: string, supplier: string, origin: string, location: string, note: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProductStatusUpdatedEvent {
      export type InputTuple = [productId: BigNumberish, previousStatus: BigNumberish, newStatus: BigNumberish, actor: AddressLike, location: string, note: string, timestamp: BigNumberish];
      export type OutputTuple = [productId: bigint, previousStatus: bigint, newStatus: bigint, actor: string, location: string, note: string, timestamp: bigint];
      export interface OutputObject {productId: bigint, previousStatus: bigint, newStatus: bigint, actor: string, location: string, note: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TwoPartnerSupplyChain extends BaseContract {
    
    connect(runner?: ContractRunner | null): TwoPartnerSupplyChain;
    waitForDeployment(): Promise<this>;

    interface: TwoPartnerSupplyChainInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MAX_DESCRIPTION_LENGTH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_LOCATION_LENGTH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_NAME_LENGTH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_NOTE_LENGTH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_ORIGIN_LENGTH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_PAGE_SIZE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    completeProduct: TypedContractMethod<
      [productId: BigNumberish, location: string, note: string, ],
      [void],
      'nonpayable'
    >
    

    
    createProduct: TypedContractMethod<
      [name: string, description: string, origin: string, location: string, note: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    getPartnerRole: TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getProduct: TypedContractMethod<
      [productId: BigNumberish, ],
      [TwoPartnerSupplyChain.ProductStructOutput],
      'view'
    >
    

    
    getProductHistory: TypedContractMethod<
      [productId: BigNumberish, ],
      [TwoPartnerSupplyChain.HistoryEntryStructOutput[]],
      'view'
    >
    

    
    getProductHistoryEntry: TypedContractMethod<
      [productId: BigNumberish, index: BigNumberish, ],
      [TwoPartnerSupplyChain.HistoryEntryStructOutput],
      'view'
    >
    

    
    getProductHistoryLength: TypedContractMethod<
      [productId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getProducts: TypedContractMethod<
      [offset: BigNumberish, limit: BigNumberish, ],
      [TwoPartnerSupplyChain.ProductStructOutput[]],
      'view'
    >
    

    
    markAsReceived: TypedContractMethod<
      [productId: BigNumberish, location: string, note: string, ],
      [void],
      'nonpayable'
    >
    

    
    markAsShipped: TypedContractMethod<
      [productId: BigNumberish, location: string, note: string, ],
      [void],
      'nonpayable'
    >
    

    
    productCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    receiver: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    supplier: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MAX_DESCRIPTION_LENGTH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_LOCATION_LENGTH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_NAME_LENGTH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_NOTE_LENGTH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_ORIGIN_LENGTH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_PAGE_SIZE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'completeProduct'): TypedContractMethod<
      [productId: BigNumberish, location: string, note: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createProduct'): TypedContractMethod<
      [name: string, description: string, origin: string, location: string, note: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getPartnerRole'): TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getProduct'): TypedContractMethod<
      [productId: BigNumberish, ],
      [TwoPartnerSupplyChain.ProductStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getProductHistory'): TypedContractMethod<
      [productId: BigNumberish, ],
      [TwoPartnerSupplyChain.HistoryEntryStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getProductHistoryEntry'): TypedContractMethod<
      [productId: BigNumberish, index: BigNumberish, ],
      [TwoPartnerSupplyChain.HistoryEntryStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getProductHistoryLength'): TypedContractMethod<
      [productId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getProducts'): TypedContractMethod<
      [offset: BigNumberish, limit: BigNumberish, ],
      [TwoPartnerSupplyChain.ProductStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'markAsReceived'): TypedContractMethod<
      [productId: BigNumberish, location: string, note: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'markAsShipped'): TypedContractMethod<
      [productId: BigNumberish, location: string, note: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'productCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'receiver'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'supplier'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'ProductCreated'): TypedContractEvent<ProductCreatedEvent.InputTuple, ProductCreatedEvent.OutputTuple, ProductCreatedEvent.OutputObject>;
getEvent(key: 'ProductStatusUpdated'): TypedContractEvent<ProductStatusUpdatedEvent.InputTuple, ProductStatusUpdatedEvent.OutputTuple, ProductStatusUpdatedEvent.OutputObject>;

    filters: {
      
      'ProductCreated(uint256,string,address,string,string,string,uint256)': TypedContractEvent<ProductCreatedEvent.InputTuple, ProductCreatedEvent.OutputTuple, ProductCreatedEvent.OutputObject>;
      ProductCreated: TypedContractEvent<ProductCreatedEvent.InputTuple, ProductCreatedEvent.OutputTuple, ProductCreatedEvent.OutputObject>;
    

      'ProductStatusUpdated(uint256,uint8,uint8,address,string,string,uint256)': TypedContractEvent<ProductStatusUpdatedEvent.InputTuple, ProductStatusUpdatedEvent.OutputTuple, ProductStatusUpdatedEvent.OutputObject>;
      ProductStatusUpdated: TypedContractEvent<ProductStatusUpdatedEvent.InputTuple, ProductStatusUpdatedEvent.OutputTuple, ProductStatusUpdatedEvent.OutputObject>;
    
    };
  }